### ISSUE TITLE
[UI/UX][IMPROVEMENT]Scrollbar to always display latest trend

### ISSUE THREAD

**Issue by aryanshridhar** [sarthakpranesh/Covid19-ReactNative#5]
Keep the horizontal scrollbar ( within India's timeline ) to always display the latest trend .

**Comment by sarthakpranesh** [comment]
Hey @aryanshridhar, thanks a lot for opening this issue. This is majorly caused bcz we are using `react-native-pure-chart` library which isn't allowing us to auto scroll to the latest trend.

We have two possible fixes two this, either we reserve the data going into the component so that the line chart plots the latest one first in this case the graph will be shown horizontally inverted or we use some other lib. We will like to know your opinion on this.

Also will you liks to work on this issue?

**Comment by aryanshridhar** [comment]
Yeah , Sure !

**Comment by sarthakpranesh** [comment]
A temporary fix was applied in #2 
Reversing the data to show the latest trends first
